import { Route } from './types';

export const APP_NAME = "Ma3Pay";

export const ROUTES: Route[] = [
  { id: '1', name: 'CBD - Langas', standardPrice: 30, peakPrice: 50 },
  { id: '2', name: 'CBD - Huruma', standardPrice: 30, peakPrice: 50 },
  { id: '3', name: 'CBD - Kapsoya', standardPrice: 40, peakPrice: 60 },
  { id: '4', name: 'CBD - Annex/Moi Uni', standardPrice: 50, peakPrice: 80 },
  { id: '5', name: 'CBD - Maili Nne', standardPrice: 40, peakPrice: 70 },
  { id: '6', name: 'CBD - Pioneer', standardPrice: 20, peakPrice: 30 },
];

export const MOCK_NFC_IDS = [
  "04:A3:5B:12:F1",
  "04:22:90:EA:33",
  "04:D1:88:4C:99"
];

export const SYSTEM_INSTRUCTION = `You are "Conductor AI", a helpful assistant for the Ma3Pay app in Eldoret, Kenya. 
Your goal is to help users navigate Eldoret's matatu system.
Key info:
- Routes: Langas, Huruma, Kapsoya, Annex, Maili Nne, Pioneer.
- Prices have Standard and Peak rates.
- Use a mix of English and Swahili.
- Be friendly and concise.`;

export const TRANSLATIONS = {
  en: {
    welcome: "Welcome",
    ready: "Ready to travel?",
    balance: "Total Balance",
    topUp: "Top Up",
    tapToRide: "Pay Fare",
    history: "History",
    weeklySpending: "Weekly Spending",
    recentActivity: "Recent Activity",
    viewAll: "View All",
    pay: "Pay",
    home: "Home",
    enterAmount: "Amount to Pay",
    phoneNumber: "Phone Number",
    payBtn: "Pay",
    matatuCode: "Enter Matatu Code",
    scanQr: "Scan QR Code",
    selectRoute: "Select Route",
    standard: "Standard",
    peak: "Peak",
    darkMode: "Dark Mode",
    language: "Language",
    login: "Login",
    createAccount: "Create Account",
    name: "Full Name",
    pin: "Secret PIN",
    register: "Register",
    logout: "Logout",
    trip: "Trip to",
    topupDesc: "M-Pesa Top Up",
    enrollTag: "Link NFC Tag",
    enrollDesc: "Scan your NFC tag to link it to your account.",
    scanToPay: "Tap Tag to Pay",
    scanToPayDesc: "Place your linked NFC tag on the device to confirm payment.",
    tagLinked: "Tag Linked Successfully",
    tagMismatch: "Wrong Tag! Use your linked tag.",
    identifyRide: "Identify Ride",
    or: "OR",
    loginTitle: "Welcome Back",
    registerTitle: "Create Account",
    switchLogin: "Already have an account? Login",
    switchRegister: "Don't have an account? Register",
    invalidPin: "Invalid Phone Number or PIN",
    userUnknown: "User not found. Please register.",
    processing: "Processing...",
    rateRide: "Rate Ride",
    rateDesc: "How was your last trip?",
    commentPlaceholder: "Tell us more (optional)...",
    submitRating: "Submit Feedback",
    ratingSuccess: "Thanks for your feedback!",
    shareTokens: "Share Tokens",
    shareDesc: "Send tokens to family & friends",
    recipientPhone: "Recipient Phone",
    transfer: "Transfer",
    transferSuccess: "Tokens Transferred Successfully",
    insufficientFunds: "Insufficient Balance"
  },
  sw: {
    welcome: "Karibu",
    ready: "Uko tayari kusafiri?",
    balance: "Salio Lako",
    topUp: "Weka Salio",
    tapToRide: "Lipa Nauli",
    history: "Historia",
    weeklySpending: "Matumizi ya Wiki",
    recentActivity: "Shughuli za Hivi Punde",
    viewAll: "Ona Zote",
    pay: "Lipa",
    home: "Nyumbani",
    enterAmount: "Kiasi cha Kulipa",
    phoneNumber: "Nambari ya Simu",
    payBtn: "Lipa",
    matatuCode: "Weka Koodi ya Matatu",
    scanQr: "Skani QR",
    selectRoute: "Chagua Njia",
    standard: "Kawaida",
    peak: "Msimu",
    darkMode: "Hali ya Giza",
    language: "Lugha",
    login: "Ingia",
    createAccount: "Fungua Akaunti",
    name: "Jina Kamili",
    pin: "PIN ya Siri",
    register: "Jisajili",
    logout: "Toka",
    trip: "Safari ya",
    topupDesc: "Kuweka Salio M-Pesa",
    enrollTag: "Unganisha Kadi",
    enrollDesc: "Skani kadi yako ya NFC kuiunganisha na akaunti.",
    scanToPay: "Gusa Kadi Kulipa",
    scanToPayDesc: "Weka kadi yako kwenye kifaa kuthibitisha malipo.",
    tagLinked: "Kadi Imeunganishwa",
    tagMismatch: "Kadi Isiyo sahihi! Tumia kadi yako.",
    identifyRide: "Chagua Safari",
    or: "AU",
    loginTitle: "Karibu Tena",
    registerTitle: "Fungua Akaunti",
    switchLogin: "Una akaunti? Ingia",
    switchRegister: "Huna akaunti? Jisajili",
    invalidPin: "Nambari au PIN si sahihi",
    userUnknown: "Hujasajiliwa. Tafadhali jisajili.",
    processing: "Inakata...",
    rateRide: "Kadiria Safari",
    rateDesc: "Safari yako ilikuwaje?",
    commentPlaceholder: "Tuambie zaidi (si lazima)...",
    submitRating: "Tuma Maoni",
    ratingSuccess: "Asante kwa maoni yako!",
    shareTokens: "Sambaza",
    shareDesc: "Tuma tokens kwa marafiki",
    recipientPhone: "Nambari ya Wapokeaji",
    transfer: "Tuma",
    transferSuccess: "Imetumwa Kikamilifu",
    insufficientFunds: "Salio Halitoshi"
  }
};